#Replace "Z" with (you guessed it) your Z

#Here you can add your Shader Path

reshadeTexturePath = /home/Z/.local/share/reshade/Textures
reshadeIncludePath = /home/Z/.local/share/reshade/Shaders

#shader file name/location

qUINT_lightroom = /home/Z/.local/share/reshade/Shaders/qUINT_lightroom.fx
Tonemap = /home/Z/.local/share/reshade/Shaders/Tonemap.fx
Levels = /home/Z/.local/share/reshade/Shaders/Levels.fx
Clarity = /home/Z/.local/share/reshade/Shaders/Clarity.fx
AdaptiveSharpen = /home/Z/.local/share/reshade/Shaders/AdaptiveSharpen.fx


casSharpness=0.0
toggleKey = F2

effects = qUINT_lightroom:Tonemap:Levels:Clarity:AdaptiveSharpen